apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: employeedb
  POSTGRES_USER: postgres
  PGDATA: /var/lib/postgresql/data/pgdata/